#!/usr/bin/env bash
# Pings the provided IP adress 5 times or else shows usage syntax
if [ -z "$1"]
    then
        echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
        exit 1
fi

ping -c 5 "$1"
